language: python
python:
  - "3.4"
# command to install dependencies
install:
  - "pip install . --use-mirrors"
  - "pip install -r requirements.txt --use-mirrors"
# command to run tests
script: nosetests